### ISSUE TITLE
--no-default-features does no longer works thus preventing building on stable

### ISSUE THREAD

**Issue by ytrezq** [Electric-Coin-Company/jubjub-prototype#10]
invite@linux:~/sources/app/jubjub-prototype$ cargo run --release --no-default-features --bin bench_50
       Compiling pairing v0.11.0
    error[E0554]: #![feature] may not be used on the stable release channel
     --> /home/invite/.cargo/registry/src/github.com-1ecc6299db9ec823/pairing-0.11.0/src/lib.rs:4:39
      |
    4 | #![cfg_attr(feature = "u128-support", feature(i128_type))]
      |                                       ^^^^^^^^^^^^^^^^^^^

    error: aborting due to previous error

    error: Could not compile `pairing`.

**Comment by daira** [comment]
This prototype code is no longer used.
