### ISSUE TITLE
Compiling no longer works with current nightly versions

### ISSUE THREAD

**Issue by ytrezq** [Electric-Coin-Company/jubjub-prototype#11]
invite@linux:~/sources/app/jubjub-prototype$ cargo run --release --bin bench_50
       Compiling libc v0.2.54
       Compiling byteorder v1.3.1
       Compiling futures v0.1.26
       Compiling crossbeam v0.3.2
       Compiling bit-vec v0.4.4
       Compiling rand v0.4.6
       Compiling num_cpus v1.10.0
       Compiling futures-cpupool v0.1.8
       Compiling rand v0.3.23
       Compiling pairing v0.11.0
       Compiling bellman v0.0.3
       Compiling jubjub v0.0.1 (/home/invite/sources/jubjub-prototype)
    error[E0463]: can't find crate for `alloc_system`
     --> src/lib.rs:4:1
      |
    4 | extern crate alloc_system;
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

    error: aborting due to previous error

    For more information about this error, try `rustc --explain E0463`.
    error: Could not compile `jubjub`.

**Comment by weikengchen** [comment]
It seems a circumvention is to remove "extern crate alloc_system" and the request for this feature on the third line in `src/lib.rs`.

**Comment by ytrezq** [comment]
> It seems a circumvention is to remove "extern crate alloc_system" and the request for this feature on the third line in src/lib.rs.

@weikengchen : which triggers other errors because of missing definitions. This is not as simple as that.

**Comment by daira** [comment]
This prototype code is no longer used.
