### ISSUE TITLE
Pending while 'cargo test testy_more_pedersen'

### ISSUE THREAD

**Issue by 3for** [Electric-Coin-Company/jubjub-prototype#12]
Even changed the code in loop:
```
 if i == 15 {
            break
        }
```
to
```
 if i == 15 {
            break
        }
```
It halts for several hours in my host with 4G RAM and 1CPU. The other 4 test passed ok.
I wanna to know what's wrong?

**Comment by daira** [comment]
This prototype code is no longer used.
