### ISSUE TITLE
Delete commented code from source files

### ISSUE THREAD

**Issue by ghost** [Electric-Coin-Company/jubjub-prototype#3]

**Comment by ghost** [comment]
https://github.com/Electric-Coin-Company/jubjub-prototype/blob/master/src/bin/bench_50.rs

First batch of comments is deleted code etc.

**Comment by ebfull** [comment]
That particular batch of comments is there so that I can quickly get rustc to avoid jemalloc for memory benchmarking. This is just a prototype so I'm not concerned with these kinds of code quality issues.
