### ISSUE TITLE
Meet a problem about ProverStream

### ISSUE THREAD

**Issue by Senlody** [Electric-Coin-Company/jubjub-prototype#7]
In case that using CircuitInput to verify the public Input.
If I fetch prepared_vk from param file like bench_50.rs:
`let mut params = ProverStream::new("p2cparams").unwrap();`
`let vk2 = params.get_vk(1).unwrap();`
`let prepared_vk = prepare_verifying_key(&vk2);`
the function verify_proof throws an Error saying "MalformedVerifyingKey"

For example, I changed the code 
`let prepared_vk = prepare_verifying_key(&params.vk);`
in #[test]test_lookup in lib.rs to
`use std::fs::File;`
`params.write(&mut File::create("lookparams").unwrap()).unwrap();`
`let mut paramread = ProverStream::new("lookparams").unwrap();`
`let vk2 = paramread.get_vk(1).unwrap();`
`let prepared_vk = prepare_verifying_key(&vk2);`
and left the rest unchanged, the test failed.

Thus problem doesn't occur when the CircuitInput is empty (like bench_50,rs).
Is it a bug of ProverStream or there is another way to deal with the situation?

**Comment by ebfull** [comment]
`get_vk` takes a number of public inputs (which you're passing as 1). That should be fine when there aren't any explicitly allocated public inputs, but if there are in your `CircuitInput`, then yeah it will error out with malformed verifying key.

**Comment by Senlody** [comment]
Thanks a lot.
The code works now.
